name: FinanceTrack-keycloak-dev

services:
  postgres:
    image: postgres:16
    container_name: FinanceTrack-keycloak-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${KC_DB_USER}
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
      POSTGRES_DB: ${KC_DB_NAME}
    volumes:
      - FinanceTrack_keycloak_db_data:/var/lib/postgresql/data
    ports:
      - "15432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:26.4.4
    container_name: FinanceTrack-keycloak
    depends_on:
      - postgres
    command: >
      start-dev
      --http-port=${KC_HTTP_PORT}
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/${KC_DB_NAME}
      KC_DB_USERNAME: ${KC_DB_USER}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}

      KC_HTTP_ENABLED: "true"
      KC_PROXY_HEADERS: xforwarded
      KC_HOSTNAME_STRICT: "false"
    ports:
      - "${KC_PUBLIC_PORT}:${KC_HTTP_PORT}"
    volumes:
      - FinanceTrack_keycloak_data:/opt/keycloak/data
      - ./exports:/temp/exports
    restart: unless-stopped

  postgres-backup:
    image: postgres:16
    container_name: FinanceTrack-keycloak-postgres-backup
    depends_on:
      - postgres
    environment:
      PGPASSWORD: ${KC_DB_PASSWORD}
    volumes:
      - FinanceTrack_keycloak_db_data:/var/lib/postgresql/data:ro
      - ./backups:/backups
    entrypoint: ["/bin/bash", "-c"]
    command: |
      while true; do
        ts=$(date +"%Y-%m-%d_%H-%M-%S");
        echo "Running backup at $ts";
        pg_dump -h postgres -U ${KC_DB_USER} -d ${KC_DB_NAME} > /backups/keycloak_$ts.sql;
        echo "Backup finished, sleeping 6h...";
        sleep 21600;
      done

  mailpit:
    image: axllent/mailpit:latest
    container_name: FinanceTrack-mailpit
    restart: unless-stopped
    ports:
      - "1025:1025"   # SMTP
      - "16020:8025"  # Web UI

volumes:
  FinanceTrack_keycloak_db_data:
  FinanceTrack_keycloak_data:
